import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1789529500326 implements MigrationInterface {
    name = 'Baseline1789529500326'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "institutions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "institution_name" character varying(200) NOT NULL, "slug" character varying(300) NOT NULL, "institution_code" character varying(50) NOT NULL, "description" character varying(500), "address" text, "phone" character varying(30), "phoneSecondary" character varying(30), "institutional_email" character varying(150), "rector_name" character varying(200), "rector_signature" text, "logo_url" text, "academic_regulation" text, "document_config" jsonb, CONSTRAINT "UQ_b0e3a0e4d706e0baaa5a7c65f22" UNIQUE ("slug"), CONSTRAINT "PK_0be7539dcdba335470dc05e9690" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_institution_slug" ON "institutions" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."academic_periods_status_enum" AS ENUM('OPEN', 'CLOSED')`);
        await queryRunner.query(`CREATE TABLE "academic_periods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "year" character varying(4) NOT NULL, "period_name" character varying(100) NOT NULL, "sequence" integer NOT NULL DEFAULT '1', "start_date" date NOT NULL, "end_date" date NOT NULL, "status" "public"."academic_periods_status_enum" NOT NULL DEFAULT 'OPEN', "career_id" uuid NOT NULL, CONSTRAINT "PK_911f414fba24e3855a5ba1f51ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_academic_career_id" ON "academic_periods" ("career_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_period_career_year" ON "academic_periods" ("career_id", "year") `);
        await queryRunner.query(`CREATE TYPE "public"."grades_status_enum" AS ENUM('APPROVED', 'FAILED', 'PENDING')`);
        await queryRunner.query(`CREATE TABLE "grades" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "first_partial" numeric(5,2), "second_partial" numeric(5,2), "practices" numeric(5,2), "final_exam" numeric(5,2), "final_grade" numeric(5,2), "status" "public"."grades_status_enum" NOT NULL DEFAULT 'PENDING', "student_id" uuid NOT NULL, "assignment_id" uuid NOT NULL, CONSTRAINT "PK_4740fb6f5df2505a48649f1687b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_grade_student_id" ON "grades" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_grade_assignment_id" ON "grades" ("assignment_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_grade_student_assignment" ON "grades" ("student_id", "assignment_id") `);
        await queryRunner.query(`CREATE TYPE "public"."attendances_status_enum" AS ENUM('PRESENT', 'ABSENT', 'LATE', 'JUSTIFIED')`);
        await queryRunner.query(`CREATE TABLE "attendances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "attendance_date" date NOT NULL, "status" "public"."attendances_status_enum" NOT NULL DEFAULT 'PRESENT', "observations" text, "student_id" uuid NOT NULL, "assignment_id" uuid NOT NULL, CONSTRAINT "PK_483ed97cd4cd43ab4a117516b69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_attendance_student_id" ON "attendances" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_attendance_assignment_id" ON "attendances" ("assignment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_attendance_student_date" ON "attendances" ("student_id", "attendance_date") `);
        await queryRunner.query(`CREATE TABLE "subject_enrollments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "student_id" uuid NOT NULL, "assignment_id" uuid NOT NULL, CONSTRAINT "PK_1bbfd69014c4b91b0aaa4f5aa04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_subject_enrollment_assignment" ON "subject_enrollments" ("assignment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_subject_enrollment_student" ON "subject_enrollments" ("student_id") `);
        await queryRunner.query(`CREATE TABLE "subject_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "parallel" character varying(20) NOT NULL DEFAULT 'A', "classroom" character varying(50), "schedule" jsonb, "subject_id" uuid NOT NULL, "teacher_id" uuid, "academic_period_id" uuid NOT NULL, "semester" integer NOT NULL, CONSTRAINT "PK_9a91b2ae451e16fcbffbcefb404" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_assignment_subject_id" ON "subject_assignments" ("subject_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_assignment_period_id" ON "subject_assignments" ("academic_period_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_assignment_subject_period" ON "subject_assignments" ("subject_id", "academic_period_id") `);
        await queryRunner.query(`CREATE TABLE "subjects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "code" character varying(30) NOT NULL, "name" character varying(200) NOT NULL, "semester" integer NOT NULL, "weekly_hours" integer NOT NULL DEFAULT '0', "total_hours" integer NOT NULL DEFAULT '0', "prerequisites" text, "is_elective" boolean NOT NULL DEFAULT false, "career_id" uuid NOT NULL, CONSTRAINT "PK_1a023685ac2b051b4e557b0b280" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_subject_career_id" ON "subjects" ("career_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_subject_career_code" ON "subjects" ("career_id", "code") `);
        await queryRunner.query(`CREATE INDEX "IDX_subject_career_semester" ON "subjects" ("career_id", "semester") `);
        await queryRunner.query(`CREATE TYPE "public"."careers_state_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "careers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "name" character varying(200) NOT NULL, "code" character varying(30) NOT NULL, "description" text, "duration_years" integer NOT NULL DEFAULT '3', "number_of_levels" integer NOT NULL DEFAULT '6', "state" "public"."careers_state_enum" NOT NULL DEFAULT 'ACTIVE', "study_plan" jsonb, "institution_id" uuid NOT NULL, CONSTRAINT "PK_febfc45dc83d58090d3122fde3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_career_code" ON "careers" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."enrollments_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "enrollments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "enrollment_number" character varying(50) NOT NULL, "enrollment_date" date NOT NULL, "status" "public"."enrollments_status_enum" NOT NULL DEFAULT 'ACTIVE', "semester" integer NOT NULL, "total_amount" numeric(12,2), "observations" text, "student_id" uuid NOT NULL, "career_id" uuid NOT NULL, "academic_period_id" uuid NOT NULL, CONSTRAINT "PK_7c0f752f9fb68bf6ed7367ab00f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_enrollment_number" ON "enrollments" ("enrollment_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_enrollment_student_id" ON "enrollments" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_enrollment_period_id" ON "enrollments" ("academic_period_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_enrollment_student_period" ON "enrollments" ("student_id", "academic_period_id") `);
        await queryRunner.query(`CREATE TYPE "public"."deposits_verification_status_enum" AS ENUM('PENDING', 'VERIFIED', 'APPROVED', 'REJECTED', 'OBSERVED')`);
        await queryRunner.query(`CREATE TABLE "deposits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "deposit_number" character varying(100) NOT NULL, "deposit_date" date NOT NULL, "amount" numeric(12,2) NOT NULL, "concept" character varying(255) NOT NULL, "voucher_url" text, "verification_status" "public"."deposits_verification_status_enum" NOT NULL DEFAULT 'PENDING', "verification_comment" text, "verification_date" TIMESTAMP WITH TIME ZONE, "verified_by" character varying(200), "student_id" uuid NOT NULL, CONSTRAINT "PK_f49ba0cd446eaf7abb4953385d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_deposit_number" ON "deposits" ("deposit_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_deposit_student" ON "deposits" ("student_id") `);
        await queryRunner.query(`CREATE TYPE "public"."employees_employee_type_enum" AS ENUM('DIRECTIVO', 'DOCENTE', 'ADMINISTRATIVO', 'APOYO')`);
        await queryRunner.query(`CREATE TABLE "employees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "employee_code" character varying(50) NOT NULL, "hire_date" date, "employee_type" "public"."employees_employee_type_enum" NOT NULL, "position" character varying(150), "person_id" uuid NOT NULL, CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_employee_code" ON "employees" ("employee_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_employee_person_id" ON "employees" ("person_id") `);
        await queryRunner.query(`CREATE TYPE "public"."persons_sex_enum" AS ENUM('MALE', 'FEMALE')`);
        await queryRunner.query(`CREATE TYPE "public"."persons_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "persons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "ci" character varying(30) NOT NULL, "ci_extension" character varying(20), "first_name" character varying(150) NOT NULL, "paternal_surname" character varying(150), "maternal_surname" character varying(150), "last_name" character varying(150) NOT NULL, "birth_date" date, "sex" "public"."persons_sex_enum", "phone" character varying(30), "email" character varying(150) NOT NULL, "address" text, "photo_url" text, "status" "public"."persons_status_enum" NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_74278d8812a049233ce41440ac7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_person_ci" ON "persons" ("ci") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_person_email" ON "persons" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."students_sex_enum" AS ENUM('MALE', 'FEMALE')`);
        await queryRunner.query(`CREATE TYPE "public"."students_academic_status_enum" AS ENUM('PRE_ENROLLED', 'ACTIVE', 'WITHDRAWN', 'GRADUATE', 'TITLED', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "firstName" character varying(150) NOT NULL, "paternal_surname" character varying(150), "maternal_surname" character varying(150), "lastName" character varying(150) NOT NULL, "diploma_number" character varying(30), "ci" character varying(30) NOT NULL, "ci_extension" character varying(20), "birth_date" date NOT NULL, "sex" "public"."students_sex_enum", "phone" character varying(30), "address" text, "email" character varying(150) NOT NULL, "photo_url" text, "student_code" character varying(50) NOT NULL, "academic_status" "public"."students_academic_status_enum" NOT NULL DEFAULT 'PRE_ENROLLED', "current_level" integer NOT NULL DEFAULT '1', "career_id" uuid, "current_period_id" uuid, "person_id" uuid, CONSTRAINT "UQ_25985d58c714a4a427ced57507b" UNIQUE ("email"), CONSTRAINT "REL_5dffbda00c34ee406d6abccbc5" UNIQUE ("person_id"), CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_student_ci" ON "students" ("ci") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_student_email" ON "students" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_student_code" ON "students" ("student_code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_student_person_id" ON "students" ("person_id") `);
        await queryRunner.query(`CREATE TYPE "public"."permissions_action_enum" AS ENUM('ALL', 'VIEW', 'CREATE', 'UPDATE', 'DELETE', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "key" character varying(100) NOT NULL, "module" character varying(100), "action" "public"."permissions_action_enum" NOT NULL DEFAULT 'OTHER', "description" character varying(250), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_permission_key" ON "permissions" ("key") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "name" character varying(100) NOT NULL, "description" character varying(250), "parent_id" uuid, "is_system" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_role_name" ON "roles" ("name") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('ADMIN', 'SECRETARY', 'TEACHER', 'STUDENT')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'BLOCKED')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "username" character varying(150) NOT NULL, "passwordHash" character varying(300) NOT NULL, "email" character varying(150) NOT NULL, "fullName" character varying(150) NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'STUDENT', "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE', "last_login" TIMESTAMP WITH TIME ZONE, "failed_attempts" integer NOT NULL DEFAULT '0', "must_change_password" boolean NOT NULL DEFAULT true, "photo_url" text, "student_id" uuid, "person_id" uuid, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "REL_4bcc4fd204f448ad671c0747ab" UNIQUE ("student_id"), CONSTRAINT "REL_5ed72dcd00d6e5a88c6a6ba3d1" UNIQUE ("person_id"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_user_username" ON "users" ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_user_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_user_student_id" ON "users" ("student_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_user_person_id" ON "users" ("person_id") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "user_id" uuid, "username" character varying(100), "action" character varying(50) NOT NULL, "module" character varying(100) NOT NULL, "entity_type" character varying(100), "entity_id" character varying(100), "previous_value" jsonb, "new_value" jsonb, "ip" character varying(50), "description" text, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_audit_user_id" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_entity_id" ON "audit_logs" ("entity_id") `);
        await queryRunner.query(`CREATE TYPE "public"."academic_history_status_enum" AS ENUM('APPROVED', 'FAILED', 'PENDING')`);
        await queryRunner.query(`CREATE TABLE "academic_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_active" boolean NOT NULL DEFAULT true, "created_by" character varying, "updated_by" character varying, "student_id" uuid NOT NULL, "career_id" uuid NOT NULL, "academic_period_id" uuid NOT NULL, "subject_id" uuid NOT NULL, "semester" integer NOT NULL, "final_grade" numeric(5,2), "status" "public"."academic_history_status_enum" NOT NULL DEFAULT 'PENDING', "is_reevaluation" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_6f486b7925de223831f6399e50c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_history_student_id" ON "academic_history" ("student_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_history_period_id" ON "academic_history" ("academic_period_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_history_student_period" ON "academic_history" ("student_id", "academic_period_id") `);
        await queryRunner.query(`ALTER TABLE "academic_periods" ADD CONSTRAINT "FK_df8b9e1374573332643fb22e413" FOREIGN KEY ("career_id") REFERENCES "careers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grades" ADD CONSTRAINT "FK_9acca493883cee3b9e8f9e01cd1" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grades" ADD CONSTRAINT "FK_361ad24212a796fb219e19b3f08" FOREIGN KEY ("assignment_id") REFERENCES "subject_assignments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD CONSTRAINT "FK_7874d0af5c1371ad4ea2152e266" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD CONSTRAINT "FK_c3fcec207dbc6038ab003dddb59" FOREIGN KEY ("assignment_id") REFERENCES "subject_assignments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subject_enrollments" ADD CONSTRAINT "FK_aae01b23fb0c3a558eaee759311" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subject_enrollments" ADD CONSTRAINT "FK_88ded84df851de9c31da06e4383" FOREIGN KEY ("assignment_id") REFERENCES "subject_assignments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subject_assignments" ADD CONSTRAINT "FK_dd6656a4a91d7662c4859ca0d8f" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subject_assignments" ADD CONSTRAINT "FK_f705d08aa7a522b5ebb70dc5f22" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subject_assignments" ADD CONSTRAINT "FK_5623af4dd7fb1a603e5f0ab89a0" FOREIGN KEY ("academic_period_id") REFERENCES "academic_periods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD CONSTRAINT "FK_f31e9e8710283a65074bbd155f9" FOREIGN KEY ("career_id") REFERENCES "careers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "careers" ADD CONSTRAINT "FK_baeafd9fc299c856d4ce0614144" FOREIGN KEY ("institution_id") REFERENCES "institutions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_307813fe255896d6ebf3e6cd55c" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_b45d9fc2b55d1ad79d6d7d3abff" FOREIGN KEY ("career_id") REFERENCES "careers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_c9fc0102746d8809738b14754ac" FOREIGN KEY ("academic_period_id") REFERENCES "academic_periods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deposits" ADD CONSTRAINT "FK_ec1b340d2963ed907421696fc33" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_bcffd813608ecb48db10645a49f" FOREIGN KEY ("person_id") REFERENCES "persons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_ef7ae3a7e1eed50ece919e84ede" FOREIGN KEY ("career_id") REFERENCES "careers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_2bd3ac050695dc9b808de95ca26" FOREIGN KEY ("current_period_id") REFERENCES "academic_periods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_5dffbda00c34ee406d6abccbc59" FOREIGN KEY ("person_id") REFERENCES "persons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_3e97eeaf865aeda0d20c0c5c509" FOREIGN KEY ("parent_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_4bcc4fd204f448ad671c0747ab4" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_5ed72dcd00d6e5a88c6a6ba3d18" FOREIGN KEY ("person_id") REFERENCES "persons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "academic_history" ADD CONSTRAINT "FK_0984d978b2201582ff08165b51d" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "academic_history" ADD CONSTRAINT "FK_bc315ad9f10c6d2f657676f97ea" FOREIGN KEY ("career_id") REFERENCES "careers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "academic_history" ADD CONSTRAINT "FK_8b7326be84b4a59f36c4b72ec39" FOREIGN KEY ("academic_period_id") REFERENCES "academic_periods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "academic_history" ADD CONSTRAINT "FK_b01bf02498ce953019fcce77ba8" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "academic_history" DROP CONSTRAINT "FK_b01bf02498ce953019fcce77ba8"`);
        await queryRunner.query(`ALTER TABLE "academic_history" DROP CONSTRAINT "FK_8b7326be84b4a59f36c4b72ec39"`);
        await queryRunner.query(`ALTER TABLE "academic_history" DROP CONSTRAINT "FK_bc315ad9f10c6d2f657676f97ea"`);
        await queryRunner.query(`ALTER TABLE "academic_history" DROP CONSTRAINT "FK_0984d978b2201582ff08165b51d"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_5ed72dcd00d6e5a88c6a6ba3d18"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_4bcc4fd204f448ad671c0747ab4"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_3e97eeaf865aeda0d20c0c5c509"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_5dffbda00c34ee406d6abccbc59"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_2bd3ac050695dc9b808de95ca26"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_ef7ae3a7e1eed50ece919e84ede"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_bcffd813608ecb48db10645a49f"`);
        await queryRunner.query(`ALTER TABLE "deposits" DROP CONSTRAINT "FK_ec1b340d2963ed907421696fc33"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_c9fc0102746d8809738b14754ac"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_b45d9fc2b55d1ad79d6d7d3abff"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_307813fe255896d6ebf3e6cd55c"`);
        await queryRunner.query(`ALTER TABLE "careers" DROP CONSTRAINT "FK_baeafd9fc299c856d4ce0614144"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP CONSTRAINT "FK_f31e9e8710283a65074bbd155f9"`);
        await queryRunner.query(`ALTER TABLE "subject_assignments" DROP CONSTRAINT "FK_5623af4dd7fb1a603e5f0ab89a0"`);
        await queryRunner.query(`ALTER TABLE "subject_assignments" DROP CONSTRAINT "FK_f705d08aa7a522b5ebb70dc5f22"`);
        await queryRunner.query(`ALTER TABLE "subject_assignments" DROP CONSTRAINT "FK_dd6656a4a91d7662c4859ca0d8f"`);
        await queryRunner.query(`ALTER TABLE "subject_enrollments" DROP CONSTRAINT "FK_88ded84df851de9c31da06e4383"`);
        await queryRunner.query(`ALTER TABLE "subject_enrollments" DROP CONSTRAINT "FK_aae01b23fb0c3a558eaee759311"`);
        await queryRunner.query(`ALTER TABLE "attendances" DROP CONSTRAINT "FK_c3fcec207dbc6038ab003dddb59"`);
        await queryRunner.query(`ALTER TABLE "attendances" DROP CONSTRAINT "FK_7874d0af5c1371ad4ea2152e266"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP CONSTRAINT "FK_361ad24212a796fb219e19b3f08"`);
        await queryRunner.query(`ALTER TABLE "grades" DROP CONSTRAINT "FK_9acca493883cee3b9e8f9e01cd1"`);
        await queryRunner.query(`ALTER TABLE "academic_periods" DROP CONSTRAINT "FK_df8b9e1374573332643fb22e413"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_history_student_period"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_history_period_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_history_student_id"`);
        await queryRunner.query(`DROP TABLE "academic_history"`);
        await queryRunner.query(`DROP TYPE "public"."academic_history_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_entity_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_user_id"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_person_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_student_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_username"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_role_name"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_permission_key"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_student_person_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_student_code"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_student_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_student_ci"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TYPE "public"."students_academic_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."students_sex_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_person_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_person_ci"`);
        await queryRunner.query(`DROP TABLE "persons"`);
        await queryRunner.query(`DROP TYPE "public"."persons_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."persons_sex_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_employee_person_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_employee_code"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP TYPE "public"."employees_employee_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_deposit_student"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_deposit_number"`);
        await queryRunner.query(`DROP TABLE "deposits"`);
        await queryRunner.query(`DROP TYPE "public"."deposits_verification_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_enrollment_student_period"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_enrollment_period_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_enrollment_student_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_enrollment_number"`);
        await queryRunner.query(`DROP TABLE "enrollments"`);
        await queryRunner.query(`DROP TYPE "public"."enrollments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_career_code"`);
        await queryRunner.query(`DROP TABLE "careers"`);
        await queryRunner.query(`DROP TYPE "public"."careers_state_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_subject_career_semester"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_subject_career_code"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_subject_career_id"`);
        await queryRunner.query(`DROP TABLE "subjects"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_assignment_subject_period"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_assignment_period_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_assignment_subject_id"`);
        await queryRunner.query(`DROP TABLE "subject_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_subject_enrollment_student"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_subject_enrollment_assignment"`);
        await queryRunner.query(`DROP TABLE "subject_enrollments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_attendance_student_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_attendance_assignment_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_attendance_student_id"`);
        await queryRunner.query(`DROP TABLE "attendances"`);
        await queryRunner.query(`DROP TYPE "public"."attendances_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_grade_student_assignment"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_grade_assignment_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_grade_student_id"`);
        await queryRunner.query(`DROP TABLE "grades"`);
        await queryRunner.query(`DROP TYPE "public"."grades_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_period_career_year"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_academic_career_id"`);
        await queryRunner.query(`DROP TABLE "academic_periods"`);
        await queryRunner.query(`DROP TYPE "public"."academic_periods_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_institution_slug"`);
        await queryRunner.query(`DROP TABLE "institutions"`);
    }

}
